---
output:
  #bookdown::html_document2: default
  #bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
documentclass: book
bibliography: references.bib
---

# Conclusion {#conclusion}

\minitoc <!-- this will include a mini table of contents-->

## Summary of findings

In conclusion, this dissertation has developed a methodology to segment an urban area into different spatial units based on its urban morphology, and assessed the degree to which these novel segmentations reflected both urban morphology and housing market dynamics. A quantitative assessment was used to investigate the degree to which the segmentations produced captured variation in house prices as a proxy for housing market dynamics: this highlighted the differences between segmentations produced using different methodologies. This form of assessment should only serve as an approximate guide to interpretation, and unqualified conclusions should not be drawn on the basis of these results.

The primary contribution of this dissertation has been methodological. Throughout the study, the effects of alternate methodologies has been examined and discussed, leading to a number of key results. The dissertation found the use of contextual characters (effectively spatial lags) to be essential to developing spatially coherent segmentations. It was also shown that segmentations can be made more 'clean' by 'transposing' the cluster labels from segmentations produced by clustering smaller base spatial units onto larger, simpler geometries, with each unit (e.g. block or H3 cell) in these geometries labelled according to the cluster label which takes up the largest proportion of the cell's area in the original segmentation. The selection of base spatial unit has been found to greatly affect the resultant segmentation, corroborating previous assertions that the spatial unit should match the distribution of the variable of interest when producing spatial clusterings of this nature. This finding also suggests that the use of other base spatial units---such as regular grids---may hamper the accurate spatial segmentation of a study area based on a (set of) variable(s). The choice of clustering algorithm was also found to be crucial to the generation of satisfactory segmentations: the substitution of one clustering algorithm for another engendered extensive changes to the segmentations produced.

## Further research

The number of parameters involved in a research methodology of this scope is such that it is not possible to examine in detail the effect of changing every possible variable; this dissertation has only focused on what may be some of the most salient of these.

Future research could build upon these findings by expanding the study area, testing the method using data from a range of cities, or indeed countries.

While this dissertation has focused on producing segmentations which accurately delineate a city based on urban morphology, there is potential to further refine these areas to ensure their suitability for use as delineating housing submarkets. This could be achieved by following the methodological improvements proposed in the previous chapter, or by incorporating a further smoothing process into the methodology.

There is potential for significant further investigation into the algorithm used in the clustering process. For example, further exploring algorithms which incorporate spatial constraints, or making use of GMM's ability to assign each datapoint (i.e. tessellation cell) a probability of cluster membership. Additionally, the goodness-of-fit of the clusters these algorithms generate could be examined with measures such as geosilhouettes [@wolf2021].

------------------------------------------------------------------------

Perhaps one overriding issue in seeking to delineate clear and defined boundaries between different urban tissues and/or housing submarkets is that the definitions of both of these concepts are contested. This is by no means to suggest that the approach/endeavour should be abandoned or that any attempt to delineate such areas is futile, but rather to recognise that to do so it to create a 'wrong'---but potentially useful---simplification of these complex concepts. As is often the case, the map's clean lines belie the complexity of the areas they seek to represent.
